version: 2

project_name: pomodoro

before:
  hooks:
    - go mod tidy

builds:
  - id: pomodoro-windows
    main: ./cmd/pomodoro/main.go
    binary: pomodoro
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw64-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -H=windowsgui
  - id: pomodoro-linux-amd64
    main: ./cmd/pomodoro/main.go
    binary: pomodoro
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - id: binaries
    ids:
      - pomodoro-windows
      - pomodoro-linux-amd64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
      - goos: linux
        formats: [tar.gz]
    files:
      - app-icon.png

nfpms:
  - id: linux-packages
    package_name: pomodoro
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: pomodoro
    description: Desktop pomodoro timer built with Go and Fyne.
    license: MIT
    formats:
      - deb
      - rpm
    ids:
      - pomodoro-linux-amd64
    bindir: /usr/bin
    contents:
      - src: ./app-icon.png
        dst: /usr/share/icons/hicolor/256x256/apps/pomodoro.png
      - src: ./packaging/pomodoro.desktop
        dst: /usr/share/applications/pomodoro.desktop

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-SHA256SUMS.txt"
  algorithm: sha256
